---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.swarm.lbswarm=${LB_SWARM:-true}
    - traefik.swarm.network=proxy
    - traefik.http.routers.webui.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.webui.rule=Host(`${DOMAIN_WEBUI?domain variable not set}`)
    - traefik.http.routers.webui.tls=true
    - traefik.http.routers.webui.middlewares=${MIDDLEWARE_SECURED_WEBUI:-default-secured@file}
    - traefik.http.routers.webui.service=webui
    - traefik.http.services.webui.loadbalancer.server.scheme=${PROTOCOL_WEBUI:-http}
    - traefik.http.services.webui.loadbalancer.server.port=${PORT_WEBUI:-8080}

x-basic-deploy-labels-ollama: &basic-deploy-labels-ollama
  labels:
    - traefik.enable=true
    - traefik.swarm.lbswarm=${LB_SWARM:-true}
    - traefik.swarm.network=proxy
    - traefik.http.routers.ollama.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.ollama.rule=Host(`${DOMAIN_OLLAMA?domain variable not set}`)
    - traefik.http.routers.ollama.tls=true
    - traefik.http.routers.ollama.middlewares=${MIDDLEWARE_SECURED_OLLAMA:-default-secured@file}
    - traefik.http.routers.ollama.service=ollama
    - traefik.http.services.ollama.loadbalancer.server.scheme=${PROTOCOL_OLLAMA:-http}
    - traefik.http.services.ollama.loadbalancer.server.port=${PORT_OLLAMA:-11434}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: any
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-8}
      memory: ${RESOURCES_LIMITS_MEMORY:-16g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-4}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-8g}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  networks:
    proxy: {}
  healthcheck:
    disable: true
  tmpfs:
    - /tmp
  restart: on-failure

################################################################################
################################################################################
################################################################################
services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  open-webui:
    # https://github.com/open-webui/open-webui/pkgs/container/open-webui
    image: ghcr.io/open-webui/open-webui:${VERSION_OPEN_WEBUI:-latest}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      SCARF_NO_ANALYTICS: ${SCARF_NO_ANALYTICS:-true}
      DO_NOT_TRACK: ${DO_NOT_TRACK:-true}
      ANONYMIZED_TELEMETRY: ${ANONYMIZED_TELEMETRY:-false}
      # USER_AGENT: TODO: ...
      # CORS_ALLOW_ORIGIN: TODO: ...
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - open-webui:/app/backend/data

  ##############################################################################
  ##############################################################################
  ##############################################################################
  ollama:
    # https://hub.docker.com/r/ollama/ollama
    image: ollama/ollama:${VERSION_OLLAMA:-rocm}
    <<: [*basic, *basic-deploy-labels-ollama]
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels-ollama]
    ports:
      - target: 11434
        published: 11434
        protocol: tcp
        mode: host
    environment:
      OLLAMA_CONTEXT_LENGTH: ${OLLAMA_CONTEXT_LENGTH:-16384}
      # HSA_OVERRIDE_GFX_VERSION: 11.0.0
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ollama:/root/.ollama
    extends:
      file: docker-hwaccel.yaml
      service: ${HWACCEL_EXTEND:-hwaccel-amd}

################################################################################
################################################################################
################################################################################
networks:
  proxy:
    external: true

volumes:
  ollama:
    name: ollama
  open-webui:
    name: open-webui
